version: '2'
services:
  grabber:
    build: ./grabber
    env_file: ./common.env
    restart: on-failure:10
    links:
      - gearman
      - mongodb
  reviewer:
    build: ./reviewer
    env_file: ./common.env
    restart: on-failure:10
    links:
      - gearman
      - mongodb
  poster:
    build: ./poster
    env_file: ./common.env
    restart: on-failure:10
    links:
      - mongodb
  telegram:
    build: ./telegram
    env_file: ./common.env
    restart: on-failure:10
    links:
      - mongodb
#      - gearman
  mongodb:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
    volumes:
      - ./storage/mongodb:/data/db
    command: --auth
    restart: on-failure:10
  gearman:
    image: kendu/gearman
    restart: on-failure:10